# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'circuit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from add_circuit import Add_Circuit
from add_browser import Add_Browser


class Ui_MainWindow(QMainWindow):
    combobox_browser_items = ["Chrome", "Opera"]
    combobox_curcuit_items = ["alpha", "charlie", "delta", "foxtrot", "hotfix", "whiskey"]
    combobox_app_items = ["app", "hub", "ops"]

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.circuit_window = Add_Circuit()
        self.browser_window = Add_Browser()
        # self.add_circuit.circuit_name[str].connect(self.add_circuit)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_app = QtWidgets.QLabel(self.centralwidget)
        self.label_app.setGeometry(QtCore.QRect(70, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_app.setFont(font)
        self.label_app.setObjectName("label_app")
        self.label_circuit = QtWidgets.QLabel(self.centralwidget)
        self.label_circuit.setGeometry(QtCore.QRect(190, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_circuit.setFont(font)
        self.label_circuit.setObjectName("label_circuit")
        self.label_browser = QtWidgets.QLabel(self.centralwidget)
        self.label_browser.setGeometry(QtCore.QRect(300, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_browser.setFont(font)
        self.label_browser.setObjectName("label_browser")
        self.comboBox_app = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_app.setGeometry(QtCore.QRect(70, 70, 69, 22))
        self.comboBox_app.setObjectName("comboBox_app")
        self.fill_combobox(self.comboBox_app, self.combobox_app_items)
        self.comboBox_circuit = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_circuit.setGeometry(QtCore.QRect(180, 70, 69, 22))
        self.comboBox_circuit.setObjectName("comboBox_circuit")
        self.fill_combobox(self.comboBox_circuit, self.combobox_curcuit_items)
        self.comboBox_browser = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_browser.setGeometry(QtCore.QRect(290, 70, 85, 22))
        self.comboBox_browser.setObjectName("comboBox_browser")
        self.fill_combobox(self.comboBox_browser, self.combobox_browser_items)
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setGeometry(QtCore.QRect(400, 70, 75, 23))
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_add_browser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_browser.setGeometry(QtCore.QRect(290, 120, 75, 23))
        self.pushButton_add_browser.setObjectName("pushButton_add_browser")
        self.pushButton_add_browser.clicked.connect(self.show_add_browser_window)
        self.pushButton_add_circuit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_circuit.setGeometry(QtCore.QRect(180, 120, 75, 23))
        self.pushButton_add_circuit.setObjectName("pushButton_add_circuit")
        self.pushButton_add_circuit.clicked.connect(self.show_add_circuit_window)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Circuit selector"))
        self.label_app.setText(_translate("MainWindow", "Application"))
        self.label_circuit.setText(_translate("MainWindow", "Circuit"))
        self.label_browser.setText(_translate("MainWindow", "Browser"))
        self.pushButton_open.setText(_translate("MainWindow", "Open"))
        self.pushButton_add_browser.setText(_translate("MainWindow", "Add browser"))
        self.pushButton_add_circuit.setText(_translate("MainWindow", "Add circuit"))

    def show_add_circuit_window(self):
        self.circuit_window.show()

    def show_add_browser_window(self):
        self.browser_window.show()

    def fill_combobox(self, combobox, items):
        for i in range(0, len(items), 1):
            combobox.addItem(items[i])

    def add_browser(self):
        self.combobox_browser_items.append("browser_name")
        self.comboBox_browser.clear()
        self.fill_combobox(self.comboBox_browser, self.combobox_browser_items)

    def add_circuit(self, circuit_name):
        self.combobox_curcuit_items.append(circuit_name)
        self.comboBox_circuit.clear()
        self.fill_combobox(self.comboBox_circuit, self.combobox_curcuit_items)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
